target-version = "py312"

exclude = [
    "lib",
]

[lint]
select = [
    "A", "ANN", "ARG", "ASYNC", "B", "BLE", "C4", "DTZ", "E", "F", "FA", "FLY", "FURB",
    "G", "I", "ICN", "INT", "ISC", "LOG", "PERF", "PIE", "PL", "PTH", "Q",
    "RET", "RSE", "RUF", "SIM", "SLF", "SLOT", "T10", "TC", "TID", "TRY", "UP", "W", "YTT"
]

ignore = ["LOG015", "PLR"]
